
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul  1 2025 15:33:49 IST (Jul  1 2025 10:03:49 UTC)

// Verification Directory fv/rcomplement 

module rcomplement(a, cin1, cin2, r, y);
  input [3:0] a;
  input cin1, cin2, r;
  output [3:0] y;
  wire [3:0] a;
  wire cin1, cin2, r;
  wire [3:0] y;
  wire c1_p, c1_q, c2_p, c2_q, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_19, n_42;
  wire n_43, n_44, n_45, n_46, t0a, t0b, t1a, t1b;
  wire t1c;
  assign y[0] = y[3];
  assign y[1] = y[3];
  assign y[2] = y[3];
  CLKBUFX2 cdn_loop_breaker(.A (c2_q), .Y (n_46));
  CLKBUFX2 cdn_loop_breaker55(.A (c2_p), .Y (n_45));
  CLKBUFX2 cdn_loop_breaker56(.A (c1_q), .Y (n_44));
  CLKBUFX2 cdn_loop_breaker57(.A (c1_p), .Y (n_43));
  CLKINVX1 g235(.A (a[1]), .Y (n_19));
  INVXL g233(.A (a[2]), .Y (n_17));
  CLKINVX1 g234(.A (a[3]), .Y (n_16));
  NOR2BX1 g345__2398(.AN (r), .B (n_12), .Y (t0b));
  NOR2BX1 g346__5107(.AN (r), .B (n_14), .Y (t0b));
  NOR2XL g347__6260(.A (r), .B (n_13), .Y (t0a));
  NOR2XL g348__4319(.A (r), .B (n_15), .Y (t0a));
  MXI2XL g349__8428(.A (c2_q), .B (n_11), .S0 (t1a), .Y (n_15));
  MXI2XL g350__5526(.A (c1_p), .B (n_10), .S0 (t1a), .Y (n_14));
  MXI2XL g351__6783(.A (c1_q), .B (n_9), .S0 (t1a), .Y (n_13));
  MXI2XL g352__3680(.A (c2_p), .B (n_8), .S0 (t1a), .Y (n_12));
  INVX1 g353(.A (c2_q), .Y (n_11));
  INVX1 g354(.A (c1_p), .Y (n_10));
  INVX1 g355(.A (c1_q), .Y (n_9));
  INVX1 g356(.A (c2_p), .Y (n_8));
  NOR2XL g364__1617(.A (r), .B (n_7), .Y (t0a));
  NOR2BX1 g365__2802(.AN (r), .B (n_6), .Y (t0b));
  MXI2XL g366__1705(.A (n_0), .B (t1a), .S0 (n_2), .Y (n_7));
  MXI2XL g367__5122(.A (n_0), .B (t1a), .S0 (n_3), .Y (n_6));
  NOR2XL g368__8246(.A (r), .B (n_4), .Y (t0a));
  NOR2BX1 g369__7098(.AN (r), .B (n_5), .Y (t0b));
  NOR2XL g370__6131(.A (n_0), .B (n_2), .Y (t1c));
  NOR2XL g371__1881(.A (n_0), .B (n_3), .Y (t1c));
  MXI2XL g372__5115(.A (n_1), .B (a[0]), .S0 (cin1), .Y (n_5));
  MXI2XL g373__7482(.A (n_1), .B (a[0]), .S0 (cin2), .Y (n_4));
  NOR2BX1 g374__4733(.AN (n_44), .B (n_0), .Y (t1c));
  NOR2BX1 g375__6161(.AN (n_46), .B (n_0), .Y (t1c));
  NOR2BX1 g376__9315(.AN (n_45), .B (n_0), .Y (t1c));
  NOR2BX1 g377__9945(.AN (n_43), .B (n_0), .Y (t1c));
  NAND2XL g378__2883(.A (cin1), .B (n_1), .Y (n_3));
  NAND2XL g379__2346(.A (cin2), .B (n_1), .Y (n_2));
  CLKINVX1 g380(.A (a[0]), .Y (n_1));
  CLKINVX1 g381(.A (t1a), .Y (n_0));
  OR2X1 g229__1666(.A (t1b), .B (t1c), .Y (n_42));
  OR2XL g382__7410(.A (t0b), .B (t0a), .Y (y[3]));
  BUFX20 g383(.A (a[1]), .Y (t1a));
  BUFX20 g384(.A (n_19), .Y (t1b));
  BUFX20 g385(.A (n_42), .Y (c1_p));
  BUFX20 g386(.A (n_19), .Y (t1a));
  BUFX20 g387(.A (1'b0), .Y (t1b));
  BUFX20 g388(.A (n_42), .Y (c1_q));
  BUFX20 g389(.A (n_17), .Y (t1a));
  BUFX20 g390(.A (1'b0), .Y (t1b));
  BUFX20 g391(.A (n_42), .Y (c2_p));
  BUFX20 g392(.A (n_17), .Y (t1a));
  BUFX20 g393(.A (1'b0), .Y (t1b));
  BUFX20 g394(.A (n_42), .Y (c2_q));
  BUFX20 g395(.A (a[3]), .Y (t1a));
  BUFX20 g396(.A (n_16), .Y (t1b));
  BUFX20 g397(.A (n_16), .Y (t1a));
  BUFX20 g398(.A (1'b0), .Y (t1b));
endmodule

